// <auto-generated />
using System;
using Academia_Central.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Academia_Central.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251023184644_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Academia_Central.Api.Models.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Alumnos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Pérez",
                            DNI = "12345678A",
                            Email = "juan@univ.edu",
                            Matricula = "ALU001",
                            Nombre = "Juan"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Gómez",
                            DNI = "87654321B",
                            Email = "ana@univ.edu",
                            Matricula = "ALU002",
                            Nombre = "Ana"
                        });
                });

            modelBuilder.Entity("Academia_Central.Api.Models.Carrera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoUnico")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DuracionAnios")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Carreras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodigoUnico = "IS-2025",
                            DuracionAnios = 5,
                            Nombre = "Ingeniería en Sistemas"
                        },
                        new
                        {
                            Id = 2,
                            CodigoUnico = "PS-2025",
                            DuracionAnios = 4,
                            Nombre = "Licenciatura en Psicología"
                        });
                });

            modelBuilder.Entity("Academia_Central.Api.Models.Matricula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlumnoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarreraId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaFinVigencia")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicioVigencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("PeriodoAcademico")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarreraId");

                    b.HasIndex("AlumnoId", "PeriodoAcademico")
                        .IsUnique();

                    b.ToTable("Matriculas");
                });

            modelBuilder.Entity("Academia_Central.Api.Models.Matricula", b =>
                {
                    b.HasOne("Academia_Central.Api.Models.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Academia_Central.Api.Models.Carrera", "Carrera")
                        .WithMany()
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Carrera");
                });
#pragma warning restore 612, 618
        }
    }
}
